version: '3.9'

networks:
  default:
    name: coding-dojo-api-golang

services:
  app:
    image: ghcr.io/valentinlutz/coding-dojo-api-golang:latest
    container_name: app
    hostname: app
    volumes:
      - ../config/config.yaml:/app/config/config.yaml:ro
    ports:
      - '8080:8080'
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 250M